version: "3"

services:
  sonarqube:
    build: 
      context: ./sonarqube/
      args:
        - VERSION=${SONAR_VERSION}
    ports:
      - "${SONARQUBE_EXTERNAL_HOST_PORT}:${SONARQUBE_INTERNAL_DOCKER_PORT}"
    environment:
      - SONARQUBE_JDBC_USERNAME=${DATABASE_USERNAME}
      - SONARQUBE_JDBC_PASSWORD=${DATABASE_PASSWORD}
      - SONARQUBE_JDBC_URL=${DATABASE_URL}
      - SONARQUBE_WEB_CONTEXT=${WEB_CONTEXT}
    networks:
      - sonarnet
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins


  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data: